import { pgTable, uuid, varchar, timestamp, integer, numeric, boolean, text, jsonb } from "drizzle-orm/pg-core"
import { users } from "./usersTable"

export const products = pgTable("products", {
    id: uuid("id").primaryKey().defaultRandom(),
    title: varchar("title", { length: 255 }).notNull(),
    ownerId: uuid("owner_id").references(() => users.id).notNull(),
    description: text("description"),
    condition: varchar("condition", { length: 50 }).notNull().default("like-new"),
    tags: jsonb("tags"),
    pricePerDay: integer("price_per_day").notNull(),
    deposit: integer("deposit"),
    depositEnabled: boolean("deposit_enabled").notNull().default(false),
    hourlyRate: integer("hourly_rate"),
    minRentalDays: integer("min_rental_days"),
    pricingRules: jsonb("pricing_rules"),
    availableRanges: jsonb("available_ranges"),
    quantity: integer("quantity").notNull().default(1),
    maxConcurrent: integer("max_concurrent").notNull().default(1),
    bufferDays: integer("buffer_days").notNull().default(0),
    address: varchar("address", { length: 255 }),
    googleMapsAddress: varchar("google_maps_address", { length: 1024 }),
    city: varchar("city", { length: 100 }),
    deliveryOption: varchar("delivery_option", { length: 50 }).notNull().default("pickup"),
    deliveryRadius: integer("delivery_radius"),
    deliveryFee: integer("delivery_fee"),
    estimatedDeliveryTime: varchar("estimated_delivery_time", { length: 100 }),
    pickupInstructions: text("pickup_instructions"),
    cancellationPolicy: varchar("cancellation_policy", { length: 50 }).notNull().default("flexible"),
    customCancellationText: text("custom_cancellation_text"),
    depositChargeType: varchar("deposit_charge_type", { length: 50 }).notNull().default("hold"),
    requireIdVerification: boolean("require_id_verification").notNull().default(false),
    requireSecurityDeposit: boolean("require_security_deposit").notNull().default(false),
    requireRenterReviews: boolean("require_renter_reviews").notNull().default(false),
    usageRules: text("usage_rules"),
    addOns: jsonb("add_ons"),
    status: varchar("status", { length: 20 }).notNull().default("draft"),
    publishDate: timestamp("publish_date"),
    category: varchar("category", { length: 100 }).notNull(),
    badge: varchar("badge", { length: 50 }),
    imageUrls: jsonb("image_urls"),
    rating: numeric("rating", { precision: 3, scale: 2 }).default('0'),
    reviewsCount: integer("reviews_count").default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    deletedAt: timestamp("deleted_at"),
});
