CREATE TABLE "products" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "title" varchar(255) NOT NULL,
    "owner_id" uuid NOT NULL,
    "description" text,
    "condition" varchar(50) NOT NULL DEFAULT 'like-new',
    "tags" jsonb,
    "price_per_day" integer NOT NULL,
    "deposit" integer,
    "deposit_enabled" boolean NOT NULL DEFAULT false,
    "hourly_rate" integer,
    "min_rental_days" integer,
    "pricing_rules" jsonb,
    "available_ranges" jsonb,
    "blocked_dates" jsonb,
    "quantity" integer NOT NULL DEFAULT 1,
    "max_concurrent" integer NOT NULL DEFAULT 1,
    "buffer_days" integer NOT NULL DEFAULT 0,
    "address" varchar(255),
    "google_maps_address" varchar(1024),
    "city" varchar(100),
    "delivery_option" varchar(50) NOT NULL DEFAULT 'pickup',
    "delivery_radius" integer,
    "delivery_fee" integer,
    "estimated_delivery_time" varchar(100),
    "pickup_instructions" text,
    "cancellation_policy" varchar(50) NOT NULL DEFAULT 'flexible',
    "custom_cancellation_text" text,
    "deposit_charge_type" varchar(50) NOT NULL DEFAULT 'hold',
    "require_id_verification" boolean NOT NULL DEFAULT false,
    "require_security_deposit" boolean NOT NULL DEFAULT false,
    "require_renter_reviews" boolean NOT NULL DEFAULT false,
    "usage_rules" text,
    "add_ons" jsonb,
    "status" varchar(20) NOT NULL DEFAULT 'draft',
    "publish_date" timestamp,
    "category" varchar(100) NOT NULL,
    "badge" varchar(50),
    "image_url" varchar(1024),
    "rating" numeric(3,2) DEFAULT '0',
    "reviews_count" integer DEFAULT 0,
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    "deleted_at" timestamp,
    CONSTRAINT "products_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users" ("id")
);
